# Generated by Django 5.1 on 2024-09-12 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djassa', '0007_alter_follow_follower'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='categorie',
            field=models.CharField(choices=[('Mode', 'Mode et Accessoires'), ('Electronique', 'Électronique et Informatique'), ('Maison', 'Maison et Jardin')], default='Mode', max_length=50),
        ),
        migrations.AddField(
            model_name='publication',
            name='fonction',
            field=models.CharField(choices=[('quasie_neuf', 'Quasi Neuf'), ('deuxieme_main', 'Deuxième Main'), ('nouveau', 'Nouveau')], default='nouveau', max_length=20),
        ),
        migrations.AddField(
            model_name='publication',
            name='nom_du_produit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
