# Generated by Django 5.1.2 on 2024-12-21 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djassa', '0009_demande'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demande',
            old_name='titre',
            new_name='nom_du_produit',
        ),
        migrations.RemoveField(
            model_name='demande',
            name='statut',
        ),
        migrations.AddField(
            model_name='demande',
            name='etat_du_produit',
            field=models.CharField(blank=True, choices=[('dans_carton', 'Dans Carton'), ('quasi_neuf', 'Quasi Neuf'), ('deuxieme_main', 'Deuxième Main')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='demande',
            name='numero_telephone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='demande',
            name='prix_achat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='demande',
            name='categorie',
            field=models.CharField(blank=True, choices=[('Mode', 'Mode et Accessoires'), ('Electronique', 'Électronique et Informatique'), ('Maison', 'Maison et Jardin')], max_length=50, null=True),
        ),
    ]
