# Generated by Django 5.1.2 on 2024-12-24 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djassa', '0010_rename_titre_demande_nom_du_produit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='followers_count',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='following_count',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='friends_count',
        ),
    ]
