# Generated by Django 5.1.6 on 2025-03-09 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djassa', '0012_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='video',
            new_name='fichier',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='image',
        ),
    ]
