# Generated by Django 5.1.6 on 2025-04-05 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djassa', '0014_vuepublication'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VuePublication',
        ),
    ]
