# Generated by Django 5.1.6 on 2025-04-09 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djassa', '0019_customuser_country_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
