# Generated by Django 5.1.6 on 2025-04-12 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djassa', '0020_customuser_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='publications_vues',
            field=models.ManyToManyField(blank=True, to='djassa.publication'),
        ),
    ]
